version: "3"
services:
  app:
    image: beslow/rocketmq_consumer:latest
    command: /bin/sh -c ./rocketmq_consumer
    environment:
      - NAME_SERVER_ADDR=192.168.1.11
      - CUSTOMER_GROUP=group-a
